package com.devops.dev.domainObject;
// Generated 1 May, 2017 6:29:41 PM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Board generated by hbm2java
 */
@Entity
@Table(name = "board")
public class Board implements java.io.Serializable {

	private int boardId;
	private String boardName;
	//private Set<ClassLevelType> classLevelTypes = new HashSet<ClassLevelType>(0);

	public Board() {
	}

	public Board(int boardId, String boardName) {
		this.boardId = boardId;
		this.boardName = boardName;
	}

	public Board(int boardId, String boardName, Set<ClassLevelType> classLevelTypes) {
		this.boardId = boardId;
		this.boardName = boardName;
		//this.classLevelTypes = classLevelTypes;
	}

	@Id
	@Column(name = "board_id", unique = true, nullable = false)
	public int getBoardId() {
		return this.boardId;
	}

	public void setBoardId(int boardId) {
		this.boardId = boardId;
	}

	@Column(name = "board_name", nullable = false, length = 45)
	public String getBoardName() {
		return this.boardName;
	}

	public void setBoardName(String boardName) {
		this.boardName = boardName;
	}

	/*@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "board")
	public Set<ClassLevelType> getClassLevelTypes() {
		return this.classLevelTypes;
	}

	public void setClassLevelTypes(Set<ClassLevelType> classLevelTypes) {
		this.classLevelTypes = classLevelTypes;
	}
*/
}
