package com.devops.dev.domainObject;
// Generated 1 May, 2017 6:29:41 PM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ClassCalendar generated by hbm2java
 */
@Entity
@Table(name = "class_calendar")
public class ClassCalendar implements java.io.Serializable {

	private int classCalendarId;
	private ClassLevelType classLevelType;
	private String month;
	private String day;
	private String year;
	private String eventName;
	private String eventDescription;
	private String eventType;
	private Set<TestResult> testResults = new HashSet<TestResult>(0);
	private Set<TakeUpDefaulterCalendar> takeUpDefaulterCalendars = new HashSet<TakeUpDefaulterCalendar>(0);

	public ClassCalendar() {
	}

	public ClassCalendar(int classCalendarId, ClassLevelType classLevelType, String month, String day, String year,
			String eventName, String eventDescription, String eventType) {
		this.classCalendarId = classCalendarId;
		this.classLevelType = classLevelType;
		this.month = month;
		this.day = day;
		this.year = year;
		this.eventName = eventName;
		this.eventDescription = eventDescription;
		this.eventType = eventType;
	}

	public ClassCalendar(int classCalendarId, ClassLevelType classLevelType, String month, String day, String year,
			String eventName, String eventDescription, String eventType, Set<TestResult> testResults,
			Set<TakeUpDefaulterCalendar> takeUpDefaulterCalendars) {
		this.classCalendarId = classCalendarId;
		this.classLevelType = classLevelType;
		this.month = month;
		this.day = day;
		this.year = year;
		this.eventName = eventName;
		this.eventDescription = eventDescription;
		this.eventType = eventType;
		this.testResults = testResults;
		this.takeUpDefaulterCalendars = takeUpDefaulterCalendars;
	}

	@Id

	@Column(name = "class_calendar_id", unique = true, nullable = false)
	public int getClassCalendarId() {
		return this.classCalendarId;
	}

	public void setClassCalendarId(int classCalendarId) {
		this.classCalendarId = classCalendarId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "class_level_type_id", nullable = false)
	public ClassLevelType getClassLevelType() {
		return this.classLevelType;
	}

	public void setClassLevelType(ClassLevelType classLevelType) {
		this.classLevelType = classLevelType;
	}

	@Column(name = "month", nullable = false, length = 45)
	public String getMonth() {
		return this.month;
	}

	public void setMonth(String month) {
		this.month = month;
	}

	@Column(name = "day", nullable = false, length = 45)
	public String getDay() {
		return this.day;
	}

	public void setDay(String day) {
		this.day = day;
	}

	@Column(name = "year", nullable = false, length = 45)
	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	@Column(name = "event_name", nullable = false, length = 45)
	public String getEventName() {
		return this.eventName;
	}

	public void setEventName(String eventName) {
		this.eventName = eventName;
	}

	@Column(name = "event_description", nullable = false, length = 45)
	public String getEventDescription() {
		return this.eventDescription;
	}

	public void setEventDescription(String eventDescription) {
		this.eventDescription = eventDescription;
	}

	@Column(name = "event_type", nullable = false, length = 45)
	public String getEventType() {
		return this.eventType;
	}

	public void setEventType(String eventType) {
		this.eventType = eventType;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "classCalendar")
	public Set<TestResult> getTestResults() {
		return this.testResults;
	}

	public void setTestResults(Set<TestResult> testResults) {
		this.testResults = testResults;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "classCalendar")
	public Set<TakeUpDefaulterCalendar> getTakeUpDefaulterCalendars() {
		return this.takeUpDefaulterCalendars;
	}

	public void setTakeUpDefaulterCalendars(Set<TakeUpDefaulterCalendar> takeUpDefaulterCalendars) {
		this.takeUpDefaulterCalendars = takeUpDefaulterCalendars;
	}

}
