package com.devops.dev.domainObject;
// Generated 1 May, 2017 6:29:41 PM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ClassLevel generated by hbm2java
 */
@Entity
@Table(name = "class_level")
public class ClassLevel implements java.io.Serializable {

	private int classLevelId;
	private String description;
	//private Set<ClassLevelType> classLevelTypes = new HashSet<ClassLevelType>(0);

	public ClassLevel() {
	}

	public ClassLevel(int classLevelId) {
		this.classLevelId = classLevelId;
	}

	public ClassLevel(int classLevelId, String description, Set<ClassLevelType> classLevelTypes) {
		this.classLevelId = classLevelId;
		this.description = description;
		//this.classLevelTypes = classLevelTypes;
	}

	@Id
	@Column(name = "class_level_id", unique = true, nullable = false)
	public int getClassLevelId() {
		return this.classLevelId;
	}

	public void setClassLevelId(int classLevelId) {
		this.classLevelId = classLevelId;
	}

	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	/*@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "classLevel")
	public Set<ClassLevelType> getClassLevelTypes() {
		return this.classLevelTypes;
	}

	public void setClassLevelTypes(Set<ClassLevelType> classLevelTypes) {
		this.classLevelTypes = classLevelTypes;
	}*/

}
