package com.devops.dev.domainObject;
// Generated 1 May, 2017 6:29:41 PM by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * HibernateSequence generated by hbm2java
 */
@Entity
@Table(name = "hibernate_sequence")
public class HibernateSequence implements java.io.Serializable {

	private Long nextVal;

	public HibernateSequence() {
	}

	public HibernateSequence(Long nextVal) {
		this.nextVal = nextVal;
	}

	@Id

	@Column(name = "next_val")
	public Long getNextVal() {
		return this.nextVal;
	}

	public void setNextVal(Long nextVal) {
		this.nextVal = nextVal;
	}

}
