package com.devops.dev.domainObject;
// Generated 1 May, 2017 6:29:41 PM by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LectureSchedule generated by hbm2java
 */
@Entity
@Table(name = "lecture_schedule")
public class LectureSchedule implements java.io.Serializable {

	private int lectureScheduleId;
	private Users users;
	private ClassLevelType classLevelType;
	private String lectureDatetime;
	private Integer subjectId;

	public LectureSchedule() {
	}

	public LectureSchedule(int lectureScheduleId) {
		this.lectureScheduleId = lectureScheduleId;
	}

	public LectureSchedule(int lectureScheduleId, Users users, ClassLevelType classLevelType, String lectureDatetime,
			Integer subjectId) {
		this.lectureScheduleId = lectureScheduleId;
		this.users = users;
		this.classLevelType = classLevelType;
		this.lectureDatetime = lectureDatetime;
		this.subjectId = subjectId;
	}

	@Id

	@Column(name = "lecture_schedule_id", unique = true, nullable = false)
	public int getLectureScheduleId() {
		return this.lectureScheduleId;
	}

	public void setLectureScheduleId(int lectureScheduleId) {
		this.lectureScheduleId = lectureScheduleId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "taken_by")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "class_level_type_id")
	public ClassLevelType getClassLevelType() {
		return this.classLevelType;
	}

	public void setClassLevelType(ClassLevelType classLevelType) {
		this.classLevelType = classLevelType;
	}

	@Column(name = "lecture_datetime", length = 45)
	public String getLectureDatetime() {
		return this.lectureDatetime;
	}

	public void setLectureDatetime(String lectureDatetime) {
		this.lectureDatetime = lectureDatetime;
	}

	@Column(name = "subject_id")
	public Integer getSubjectId() {
		return this.subjectId;
	}

	public void setSubjectId(Integer subjectId) {
		this.subjectId = subjectId;
	}

}
