package com.devops.dev.domainObject;
// Generated 1 May, 2017 6:29:41 PM by Hibernate Tools 3.2.2.GA

import javax.persistence.*;

/**
 * StudentDetail generated by hbm2java
 */
@Entity
@Table(name = "student_detail")
public class StudentDetail implements java.io.Serializable {

	private int studentDetailId;
	private Users users;
	private ClassLevelType classLevelType;

	public StudentDetail() {
	}

	public StudentDetail(int studentDetailId, Users users, ClassLevelType classLevelType) {
		this.studentDetailId = studentDetailId;
		this.users = users;
		this.classLevelType = classLevelType;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "student_detail_id", unique = true, nullable = false)
	public int getStudentDetailId() {
		return this.studentDetailId;
	}

	public void setStudentDetailId(int studentDetailId) {
		this.studentDetailId = studentDetailId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "student_id", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "class_level_type_id", nullable = false)
	public ClassLevelType getClassLevelType() {
		return this.classLevelType;
	}

	public void setClassLevelType(ClassLevelType classLevelType) {
		this.classLevelType = classLevelType;
	}

}
